### ISSUE TITLE
cards broken in dev

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/petabencana.id#147]
```ERROR [app-router] Error: Error invoking Cards. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: Cannot read property 'data_server' of undefined
Inner Error Stack:
TypeError: Cannot read property 'data_server' of undefined
    at new Cards (https://dev.petabencana.id/scripts/app-bundle.js:1410:34)
    at Object.invoke (https://dev.petabencana.id/scripts/vendor-bundle.js:11806:14)
    at InvocationHandler.invoke (https://dev.petabencana.id/scripts/vendor-bundle.js:11771:168)
    at Container.invoke (https://dev.petabencana.id/scripts/vendor-bundle.js:12035:25)
    at StrategyResolver.get (https://dev.petabencana.id/scripts/vendor-bundle.js:11488:37)
    at Container.get (https://dev.petabencana.id/scripts/vendor-bundle.js:11974:23)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:23738:73
    at tryCatcher (https://dev.petabencana.id/scripts/vendor-bundle.js:3373:23)
    at Promise._settlePromiseFromHandler (https://dev.petabencana.id/scripts/vendor-bundle.js:2590:31)
    at Promise._settlePromise (https://dev.petabencana.id/scripts/vendor-bundle.js:2647:18)
    at Promise._settlePromise0 (https://dev.petabencana.id/scripts/vendor-bundle.js:2692:10)
    at Promise._settlePromises (https://dev.petabencana.id/scripts/vendor-bundle.js:2771:18)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:153:25
End Inner Error Stack
------------------------------------------------

    at new Cards (https://dev.petabencana.id/scripts/app-bundle.js:1410:34)
    at Object.invoke (https://dev.petabencana.id/scripts/vendor-bundle.js:11806:14)
    at InvocationHandler.invoke (https://dev.petabencana.id/scripts/vendor-bundle.js:11771:168)
    at Container.invoke (https://dev.petabencana.id/scripts/vendor-bundle.js:12035:25)
    at StrategyResolver.get (https://dev.petabencana.id/scripts/vendor-bundle.js:11488:37)
    at Container.get (https://dev.petabencana.id/scripts/vendor-bundle.js:11974:23)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:23738:73
    at tryCatcher (https://dev.petabencana.id/scripts/vendor-bundle.js:3373:23)
    at Promise._settlePromiseFromHandler (https://dev.petabencana.id/scripts/vendor-bundle.js:2590:31)
    at Promise._settlePromise (https://dev.petabencana.id/scripts/vendor-bundle.js:2647:18)
    at Promise._settlePromise0 (https://dev.petabencana.id/scripts/vendor-bundle.js:2692:10)
    at Promise._settlePromises (https://dev.petabencana.id/scripts/vendor-bundle.js:2771:18)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:153:25
End Inner Error Stack
------------------------------------------------

    at new Cards (https://dev.petabencana.id/scripts/app-bundle.js:1410:34)
    at Object.invoke (https://dev.petabencana.id/scripts/vendor-bundle.js:11806:14)
    at InvocationHandler.invoke (https://dev.petabencana.id/scripts/vendor-bundle.js:11771:168)
    at Container.invoke (https://dev.petabencana.id/scripts/vendor-bundle.js:12035:25)
    at StrategyResolver.get (https://dev.petabencana.id/scripts/vendor-bundle.js:11488:37)
    at Container.get (https://dev.petabencana.id/scripts/vendor-bundle.js:11974:23)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:23738:73
    at new AggregateError (https://dev.petabencana.id/scripts/vendor-bundle.js:14656:13)
    at Container.invoke (https://dev.petabencana.id/scripts/vendor-bundle.js:12037:15)
    at StrategyResolver.get (https://dev.petabencana.id/scripts/vendor-bundle.js:11488:37)
    at Container.get (https://dev.petabencana.id/scripts/vendor-bundle.js:11974:23)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:23738:73
From previous event:
    at CompositionEngine.ensureViewModel (https://dev.petabencana.id/scripts/vendor-bundle.js:23731:75)
    at TemplatingRouteLoader.loadRoute (https://dev.petabencana.id/scripts/vendor-bundle.js:24835:37)
    at loadComponent (https://dev.petabencana.id/scripts/vendor-bundle.js:18737:24)
    at loadRoute (https://dev.petabencana.id/scripts/vendor-bundle.js:18710:12)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:18674:14
    at Array.map (native)
    at loadNewRoute (https://dev.petabencana.id/scripts/vendor-bundle.js:18673:31)
    at LoadRouteStep.run (https://dev.petabencana.id/scripts/vendor-bundle.js:18665:14)
    at next (https://dev.petabencana.id/scripts/vendor-bundle.js:17408:20)
    at iterate (https://dev.petabencana.id/scripts/vendor-bundle.js:18431:14)
    at processDeactivatable (https://dev.petabencana.id/scripts/vendor-bundle.js:18434:12)
    at CanDeactivatePreviousStep.run (https://dev.petabencana.id/scripts/vendor-bundle.js:18366:14)
    at next (https://dev.petabencana.id/scripts/vendor-bundle.js:17408:20)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:17857:16
From previous event:
    at BuildNavigationPlanStep.run (https://dev.petabencana.id/scripts/vendor-bundle.js:17855:58)
    at next (https://dev.petabencana.id/scripts/vendor-bundle.js:17408:20)
    at Pipeline.run (https://dev.petabencana.id/scripts/vendor-bundle.js:17421:14)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:18994:25
From previous event:
    at AppRouter._dequeueInstruction (https://dev.petabencana.id/scripts/vendor-bundle.js:18967:32)
    at AppRouter.activate (https://dev.petabencana.id/scripts/vendor-bundle.js:18944:12)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:18914:31
From previous event:
    at https://dev.petabencana.id/scripts/vendor-bundle.js:18913:24
    at https://dev.petabencana.id/scripts/vendor-bundle.js:18919:16
    at AppRouter.registerViewPort (https://dev.petabencana.id/scripts/vendor-bundle.js:18926:10)
    at new RouterView (https://dev.petabencana.id/scripts/vendor-bundle.js:24951:19)
    at Object.invokeWithDynamicDependencies (https://dev.petabencana.id/scripts/vendor-bundle.js:11789:20)
    at InvocationHandler.invoke (https://dev.petabencana.id/scripts/vendor-bundle.js:11771:168)
    at Container.invoke (https://dev.petabencana.id/scripts/vendor-bundle.js:12035:25)
    at ProviderResolver.get (https://dev.petabencana.id/scripts/vendor-bundle.js:21279:74)
    at Container.get (https://dev.petabencana.id/scripts/vendor-bundle.js:11974:23)
    at Container.elementContainerGet [as get] (https://dev.petabencana.id/scripts/vendor-bundle.js:21334:17)
    at HtmlBehaviorResource.create (https://dev.petabencana.id/scripts/vendor-bundle.js:23287:58)
    at applyInstructions (https://dev.petabencana.id/scripts/vendor-bundle.js:21436:33)
    at ViewFactory.create (https://dev.petabencana.id/scripts/vendor-bundle.js:21657:9)
    at HtmlBehaviorResource.create (https://dev.petabencana.id/scripts/vendor-bundle.js:23299:41)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:23721:18
From previous event:
    at CompositionEngine.createController (https://dev.petabencana.id/scripts/vendor-bundle.js:23720:10)
    at CompositionEngine._createControllerAndSwap (https://dev.petabencana.id/scripts/vendor-bundle.js:23686:19)
    at CompositionEngine.compose (https://dev.petabencana.id/scripts/vendor-bundle.js:23766:21)
    at TemplatingEngine.compose (https://dev.petabencana.id/scripts/vendor-bundle.js:24034:38)
    at Aurelia.setRoot (https://dev.petabencana.id/scripts/vendor-bundle.js:12636:21)
    at https://dev.petabencana.id/scripts/app-bundle.js:82:16
From previous event:
    at Object.configure (https://dev.petabencana.id/scripts/app-bundle.js:81:21)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:12227:22
From previous event:
    at config (https://dev.petabencana.id/scripts/vendor-bundle.js:12222:48)
    at handleApp (https://dev.petabencana.id/scripts/vendor-bundle.js:12213:12)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:12246:13
From previous event:
    at https://dev.petabencana.id/scripts/vendor-bundle.js:12244:40
From previous event:
    at https://dev.petabencana.id/scripts/vendor-bundle.js:12243:29
From previous event:
    at run (https://dev.petabencana.id/scripts/vendor-bundle.js:12239:26)
    at Object.<anonymous> (https://dev.petabencana.id/scripts/vendor-bundle.js:12266:3)
    at Object.execCb (https://dev.petabencana.id/scripts/vendor-bundle.js:5432:33)
    at Module.check (https://dev.petabencana.id/scripts/vendor-bundle.js:4620:51)
    at Module.enable (https://dev.petabencana.id/scripts/vendor-bundle.js:4912:22)
    at Object.enable (https://dev.petabencana.id/scripts/vendor-bundle.js:5293:39)
    at Module.<anonymous> (https://dev.petabencana.id/scripts/vendor-bundle.js:4897:33)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:3873:23
    at each (https://dev.petabencana.id/scripts/vendor-bundle.js:3798:31)
    at Module.enable (https://dev.petabencana.id/scripts/vendor-bundle.js:4849:17)
    at Module.init (https://dev.petabencana.id/scripts/vendor-bundle.js:4525:26)
    at https://dev.petabencana.id/scripts/vendor-bundle.js:5196:36
error @ vendor-bundle.js:15983
```

**Comment by matthewberryman** [comment]
@ojha-url Looks like something in your refactor 5b39f3c6e4a7d5fbfa98599c7b8a2dc06ce99ba8 has broken the build

**Comment by matthewberryman** [comment]
@ojha-url heads up that I now have a Telegram bot CognicityDevBot running against our dev environment that you can use to generate cards (or use postman against the api on data-dev.petabencana.id but you'd need to get the new dev API key)

**Comment by ojha-url** [comment]
Thanks @matthewberryman, this will be of help without disturbing the prod database.
